"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { generateQR } from "../../utils/qrcode";

export type PixPaymentStatus =
  | "idle"
  | "qr_generated"
  | "waiting_payment"
  | "paid"
  | "expired"
  | "failed";

/**
 * UI-only Pix payment component. Does NOT process payments.
 *
 * The consumer is responsible for:
 * 1. Generating the EMV/BRCode payload on their backend (via their PSP)
 * 2. Passing it as `pixCode` (or a pre-rendered QR image via `qrCodeUrl`)
 * 3. Polling their backend for payment confirmation and updating `status`
 *
 * When no `pixCode` is provided, a placeholder QR is shown with a demo label.
 */
export interface PixPaymentProps {
  /** Payment amount in BRL (e.g. 149.90) */
  amount: number;
  /**
   * Pix copia e cola payload (EMV/BRCode format).
   * Must be generated by your payment backend (PSP).
   * When omitted, a demo placeholder is displayed.
   */
  pixCode?: string;
  /** Pre-rendered QR code image URL — bypasses client-side generation */
  qrCodeUrl?: string;
  /** Expiration time in seconds (default 300) */
  expiresIn?: number;
  /** Beneficiary display name */
  beneficiary?: string;
  /** Called when the user copies the Pix code */
  onCopy?: () => void;
  /** Called when the payment is confirmed (consumer provides polling logic) */
  onPayment?: () => void;
  /** Called when the QR code expires */
  onExpired?: () => void;
  /** Controlled status */
  status?: PixPaymentStatus;
  className?: string;
}

function formatBRL(value: number): string {
  return value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" });
}

function formatTime(seconds: number): string {
  const m = Math.floor(seconds / 60);
  const s = seconds % 60;
  return `${m}:${s.toString().padStart(2, "0")}`;
}

function QRCodeSVG({ data, size = 200 }: { data: string; size?: number }) {
  const qr = useMemo(() => {
    try {
      return generateQR(data);
    } catch {
      return null;
    }
  }, [data]);

  if (!qr) return null;

  const cellSize = size / (qr.size + 8);
  const offset = cellSize * 4;

  return (
    <svg viewBox={`0 0 ${size} ${size}`} width={size} height={size} className="block">
      <rect width={size} height={size} fill="white" rx={8} />
      {qr.matrix.map((row, r) =>
        row.map((cell, c) =>
          cell ? (
            <rect
              key={`${r}-${c}`}
              x={offset + c * cellSize}
              y={offset + r * cellSize}
              width={cellSize + 0.5}
              height={cellSize + 0.5}
              fill="#171717"
            />
          ) : null
        )
      )}
      {/* Pix icon overlay */}
      <g transform={`translate(${size / 2}, ${size / 2})`}>
        <rect x={-16} y={-16} width={32} height={32} rx={6} fill="white" />
        <rect x={-13} y={-13} width={26} height={26} rx={4} fill="#32BCAD" />
        <path
          d="M-3.5 -5.5L0 -2L3.5 -5.5M3.5 -5.5L7 -2L3.5 1.5M3.5 1.5L0 5L-3.5 1.5M-3.5 1.5L-7 -2L-3.5 -5.5"
          stroke="white"
          strokeWidth={1.8}
          fill="none"
          strokeLinecap="round"
          strokeLinejoin="round"
        />
      </g>
    </svg>
  );
}

const DEMO_PIX_CODE = "00020126580014br.gov.bcb.pix0136demo-brasa-ui-placeholder5204000053039865802BR";

export function PixPayment({
  amount,
  pixCode,
  qrCodeUrl,
  expiresIn = 300,
  beneficiary,
  onCopy,
  onPayment,
  onExpired,
  status: controlledStatus,
  className = "",
}: PixPaymentProps) {
  const isDemo = !pixCode && !qrCodeUrl;
  const effectivePixCode = pixCode || DEMO_PIX_CODE;

  const [internalStatus, setInternalStatus] = useState<PixPaymentStatus>("qr_generated");
  const [timeLeft, setTimeLeft] = useState(expiresIn);
  const [copied, setCopied] = useState(false);

  const status = controlledStatus ?? internalStatus;

  useEffect(() => {
    if (status !== "qr_generated" && status !== "waiting_payment") return;
    if (timeLeft <= 0) {
      setInternalStatus("expired");
      onExpired?.();
      return;
    }
    const timer = setInterval(() => setTimeLeft((t) => t - 1), 1000);
    return () => clearInterval(timer);
  }, [status, timeLeft, onExpired]);

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(effectivePixCode);
    setCopied(true);
    setInternalStatus("waiting_payment");
    onCopy?.();
    setTimeout(() => setCopied(false), 2000);
  }, [effectivePixCode, onCopy]);

  const timerColor =
    timeLeft > 120 ? "text-emerald-600" : timeLeft > 30 ? "text-amber-600" : "text-red-600";
  const timerBg =
    timeLeft > 120 ? "bg-emerald-50" : timeLeft > 30 ? "bg-amber-50" : "bg-red-50";

  if (status === "paid") {
    return (
      <div className={`rounded-2xl border border-emerald-200 bg-gradient-to-b from-emerald-50 to-white p-8 text-center ${className}`}>
        <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-emerald-100 ring-4 ring-emerald-50">
          <svg className="h-7 w-7 text-emerald-600" fill="none" viewBox="0 0 24 24" strokeWidth={2.5} stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
          </svg>
        </div>
        <p className="text-lg font-bold text-emerald-900">Pagamento confirmado</p>
        <p className="mt-1 text-sm font-medium text-emerald-700">{formatBRL(amount)}</p>
        {beneficiary && <p className="mt-0.5 text-xs text-emerald-600/70">para {beneficiary}</p>}
      </div>
    );
  }

  if (status === "expired") {
    return (
      <div className={`rounded-2xl border border-neutral-200 bg-gradient-to-b from-neutral-50 to-white p-8 text-center ${className}`}>
        <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-neutral-100">
          <svg className="h-7 w-7 text-neutral-400" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        </div>
        <p className="text-lg font-bold text-neutral-900">QR Code expirado</p>
        <p className="mt-1 text-sm text-neutral-500">Gere um novo código para continuar</p>
      </div>
    );
  }

  if (status === "failed") {
    return (
      <div className={`rounded-2xl border border-red-200 bg-gradient-to-b from-red-50 to-white p-8 text-center ${className}`}>
        <div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-full bg-red-100">
          <svg className="h-7 w-7 text-red-600" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 9v3.75m-9.303 3.376c-.866 1.5.217 3.374 1.948 3.374h14.71c1.73 0 2.813-1.874 1.948-3.374L13.949 3.378c-.866-1.5-3.032-1.5-3.898 0L2.697 16.126zM12 15.75h.007v.008H12v-.008z" />
          </svg>
        </div>
        <p className="text-lg font-bold text-neutral-900">Erro no pagamento</p>
        <p className="mt-1 text-sm text-neutral-500">Tente novamente ou use outro método</p>
      </div>
    );
  }

  return (
    <div className={`overflow-hidden rounded-2xl border border-neutral-200 bg-white shadow-sm ${className}`}>
      {/* Header */}
      <div className="border-b border-neutral-100 bg-gradient-to-r from-neutral-50 to-white px-6 py-4">
        <div className="flex items-center gap-3">
          <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#32BCAD]">
            <svg viewBox="0 0 24 24" className="h-4 w-4 text-white" fill="none" stroke="currentColor" strokeWidth={2.2}>
              <path d="M7 10l3-3 3 3M13 10l3-3 3 3M13 14l3 3 3-3M7 14l3 3 3-3" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
          </div>
          <div>
            <p className="text-xs font-medium uppercase tracking-wider text-neutral-400">Pagar com Pix</p>
            <p className="text-xl font-bold tracking-tight text-neutral-900">{formatBRL(amount)}</p>
          </div>
        </div>
        {beneficiary && (
          <p className="mt-1 pl-11 text-xs text-neutral-500">para {beneficiary}</p>
        )}
      </div>

      {/* QR Code */}
      <div className="flex flex-col items-center px-6 py-6">
        <div className="relative rounded-xl border border-neutral-100 bg-white p-2 shadow-sm">
          {qrCodeUrl ? (
            <img
              src={qrCodeUrl}
              alt="QR Code Pix"
              width={180}
              height={180}
              className="block rounded-lg"
            />
          ) : (
            <QRCodeSVG data={effectivePixCode} size={180} />
          )}
          {isDemo && (
            <div className="absolute -top-2 -right-2 rounded-full bg-amber-500 px-2 py-0.5 text-[10px] font-bold text-white shadow-sm">
              DEMO
            </div>
          )}
        </div>

        {/* Timer */}
        <div className={`mt-4 inline-flex items-center gap-1.5 rounded-full px-3 py-1 ${timerBg}`}>
          <svg className={`h-3.5 w-3.5 ${timerColor}`} fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" d="M12 6v6h4.5m4.5 0a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span className={`font-mono text-xs font-semibold ${timerColor}`}>
            {formatTime(timeLeft)}
          </span>
        </div>
      </div>

      {/* Copy button */}
      <div className="border-t border-neutral-100 px-6 py-4">
        <button
          type="button"
          onClick={handleCopy}
          className={`flex w-full items-center justify-center gap-2 rounded-xl px-4 py-3 text-sm font-semibold transition-all ${
            copied
              ? "bg-emerald-600 text-white"
              : "bg-neutral-900 text-white hover:bg-neutral-800 active:scale-[0.98]"
          }`}
        >
          {copied ? (
            <>
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={2.5} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M4.5 12.75l6 6 9-13.5" />
              </svg>
              Código copiado!
            </>
          ) : (
            <>
              <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M8.25 7.5V6.108c0-1.135.845-2.098 1.976-2.192.373-.03.748-.057 1.123-.08M15.75 18H18a2.25 2.25 0 002.25-2.25V6.108c0-1.135-.845-2.098-1.976-2.192a48.424 48.424 0 00-1.123-.08M15.75 18.75v-1.875a3.375 3.375 0 00-3.375-3.375h-1.5a1.125 1.125 0 01-1.125-1.125v-1.5A3.375 3.375 0 006.375 7.5H5.25m11.9-3.664A2.251 2.251 0 0015 2.25h-1.5a2.251 2.251 0 00-2.15 1.586m5.8 0c.065.21.1.433.1.664v.75h-6V4.5c0-.231.035-.454.1-.664M6.75 7.5H4.875c-.621 0-1.125.504-1.125 1.125v12c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V16.5a9 9 0 00-9-9z" />
              </svg>
              Copiar código Pix
            </>
          )}
        </button>
        {status === "waiting_payment" && (
          <p className="mt-2 text-center text-xs text-neutral-400">
            Cole o código no app do seu banco para pagar
          </p>
        )}
      </div>
    </div>
  );
}
